### ISSUE TITLE
Ends with Error: ENOENT 

### ISSUE THREAD

**Issue by Nancyeleanor** [cocktailpeanutlabs/storydiffusion-comics#2]
this is the error in the terminal

C:\pinokio\api\storydiffusion-comics\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\pinokio\api\storydiffusion-comics\app\env\Scr
ipts\activate C:\pinokio\api\storydiffusion-comics\app\env && python app.py

C:\pinokio\api\storydiffusion-comics\app\env\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `to
rch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
C:\pinokio\api\storydiffusion-comics\app\env\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `to
rch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
C:\pinokio\api\storydiffusion-comics\app\env\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `to
rch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\pinokio\api\storydiffusion-comics\app\app.py", line 15, in <module>
    from utils.gradio_utils import is_torch2_available
  File "C:\pinokio\api\storydiffusion-comics\app\utils\__init__.py", line 2, in <module>
    from .pipeline import PhotoMakerStableDiffusionXLPipeline
  File "C:\pinokio\api\storydiffusion-comics\app\utils\pipeline.py", line 13, in <module>
    from diffusers import StableDiffusionXLPipeline
  File "C:\pinokio\api\storydiffusion-comics\app\env\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\pinokio\api\storydiffusion-comics\app\env\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\pinokio\api\storydiffusion-comics\app\env\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\pinokio\api\storydiffusion-comics\app\env\lib\site-packages\huggingface_hub\__init__.py)

(env) (base) C:\pinokio\api\storydiffusion-comics\app>

**Comment by 42PAL** [comment]
same error I think:
ENOENT: no such file or directory, stat 'E:\AIStuff\ImageCreation\pinokio\api\storydiffusion-comics.git\{{input.event[0]}}'

**Comment by techcow2** [comment]
For the record the directory does exist. 
![image](https://github.com/user-attachments/assets/dd3ed164-9e2a-4a55-979b-70d41fbaf81a)

**Comment by Ho-gyo** [comment]
useless, it does not work at all!!!!!!!
